package com.example.ratepco2

import android.app.Application
import dagger.hilt.android.HiltAndroidApp

@HiltAndroidApp
class RatepCO2Application: Application() {
    val authHeaderToken = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI0IiwianRpIjoiODFkNjNkN2Y3Zjk5OWI1ZDdkMTUyMmFhNzhmY2JhOTk4MjJlNDE1NjZkZmQ3NzMxNmE4NmMzNzYyMTllNjk1NGNlYTFjYjA4MDEzYTNkOTUiLCJpYXQiOjE2NjQxMDk5MDIsIm5iZiI6MTY2NDEwOTkwMiwiZXhwIjoxNjk1NjQ1OTAyLCJzdWIiOiIxNTk0Iiwic2NvcGVzIjpbXX0.lZUOdgbW0hk9n3eJ7jgKgJwwwQGybkJCbOL9zDHx-Uf-oKPFmLjvHpon9rBhaWw2blgQQHoeTs3BGnCSZUiHjg"
}